<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="14" ignored="0" total="17" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="440997" started-at="2018-09-27T09:05:16Z" finished-at="2018-09-27T09:12:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="440997" started-at="2018-09-27T09:05:16Z" finished-at="2018-09-27T09:12:37Z">
      <class name="com.main.FlowEInvoice">
        <test-method status="PASS" signature="startReport()[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="startReport" is-config="true" duration-ms="4117" started-at="2018-09-27T09:05:16Z" finished-at="2018-09-27T09:05:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="Login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.main.FlowEInvoice@7a3d45bd]" name="Login" duration-ms="60447" started-at="2018-09-27T09:05:21Z" data-provider="Login" finished-at="2018-09-27T09:06:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[eInvoice]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[shilki.jaiswal]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[June@1811]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[ZCS Production]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[GDQA-P2P@zycus.com]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="3" started-at="2018-09-27T09:06:22Z" finished-at="2018-09-27T09:06:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login status=SUCCESS method=FlowEInvoice.Login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="InvoiceNonPO(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:com.main.FlowEInvoice@7a3d45bd]" name="InvoiceNonPO" duration-ms="153" started-at="2018-09-27T09:06:22Z" data-provider="InvoiceNonPO" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:06:22Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: InvoiceNonPO([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) GDQA_SUPPLIER,(java.lang.String) NET30,(java.lang.String) INR,(java.lang.String) 19/06/2018,(java.lang.String) CMD-sanity,(java.lang.String) 70,(java.lang.String) test,(java.lang.String) Materials testing,(java.lang.String) 32189,(java.lang.String) 1000,(java.lang.String) GLTYPE011,(java.lang.String) QMS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: InvoiceNonPO([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=9, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) GDQA_SUPPLIER,(java.lang.String) NET30,(java.lang.String) INR,(java.lang.String) 19/06/2018,(java.lang.String) CMD-sanity,(java.lang.String) 70,(java.lang.String) test,(java.lang.String) Materials testing,(java.lang.String) 32189,(java.lang.String) 1000,(java.lang.String) GLTYPE011,(java.lang.String) QMS]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvoiceNonPO -->
        <test-method status="FAIL" signature="InvoiceAction()[pri:5, instance:com.main.FlowEInvoice@7a3d45bd]" name="InvoiceAction" duration-ms="33395" started-at="2018-09-27T09:06:22Z" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:06:55Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at common.Functions.eInvoice_CommonFunctions.navigate_path(eInvoice_CommonFunctions.java:128)
at com.main.FlowEInvoice.InvoiceAction(FlowEInvoice.java:171)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvoiceAction -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="1" started-at="2018-09-27T09:06:55Z" finished-at="2018-09-27T09:06:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvoiceAction status=FAILURE method=FlowEInvoice.InvoiceAction()[pri:5, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="searchPurchaseOrders(java.lang.String, java.lang.String, java.lang.String)[pri:6, instance:com.main.FlowEInvoice@7a3d45bd]" name="searchPurchaseOrders" duration-ms="8227" started-at="2018-09-27T09:06:55Z" data-provider="PurchaseOrders" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:07:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Line Level Deployment -/610]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[GDQA_SUPPLIER]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Steffy TL]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:167)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:138)
at com.main.FlowEInvoice.searchPurchaseOrders(FlowEInvoice.java:195)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchPurchaseOrders -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:07:04Z" finished-at="2018-09-27T09:07:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=searchPurchaseOrders status=FAILURE method=FlowEInvoice.searchPurchaseOrders(java.lang.String, java.lang.String, java.lang.String)[pri:6, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="ConfigureOOO()[pri:7, instance:com.main.FlowEInvoice@7a3d45bd]" name="ConfigureOOO" duration-ms="33153" started-at="2018-09-27T09:07:04Z" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:07:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:189)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.ConfigureOOO(FlowEInvoice.java:220)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureOOO -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:07:37Z" finished-at="2018-09-27T09:07:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ConfigureOOO status=FAILURE method=FlowEInvoice.ConfigureOOO()[pri:7, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="CreditMemowithoutReference(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:8, instance:com.main.FlowEInvoice@7a3d45bd]" name="CreditMemowithoutReference" duration-ms="69" started-at="2018-09-27T09:07:37Z" data-provider="CreditMemowithoutReference" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:07:37Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: CreditMemowithoutReference([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) GDQA_SUPPLIER,(java.lang.String) INR,(java.lang.String) 20/06/2018,(java.lang.String) CMD-sanity,(java.lang.String) 70,(java.lang.String) test,(java.lang.String) Materials testing,(java.lang.String) 32189,(java.lang.String) 1000,(java.lang.String) GLTYPE011,(java.lang.String) QMS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: CreditMemowithoutReference([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=4, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=5, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=6, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=7, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=8, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) GDQA_SUPPLIER,(java.lang.String) INR,(java.lang.String) 20/06/2018,(java.lang.String) CMD-sanity,(java.lang.String) 70,(java.lang.String) test,(java.lang.String) Materials testing,(java.lang.String) 32189,(java.lang.String) 1000,(java.lang.String) GLTYPE011,(java.lang.String) QMS]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditMemowithoutReference -->
        <test-method status="FAIL" signature="CreditMemoagainstPO()[pri:9, instance:com.main.FlowEInvoice@7a3d45bd]" name="CreditMemoagainstPO" duration-ms="33281" started-at="2018-09-27T09:07:37Z" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:08:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:189)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.CreditMemoagainstPO(FlowEInvoice.java:243)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreditMemoagainstPO -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:08:10Z" finished-at="2018-09-27T09:08:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreditMemoagainstPO status=FAILURE method=FlowEInvoice.CreditMemoagainstPO()[pri:9, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="InvoiceagainstPO()[pri:10, instance:com.main.FlowEInvoice@7a3d45bd]" name="InvoiceagainstPO" duration-ms="33241" started-at="2018-09-27T09:08:10Z" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:08:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:189)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.InvoiceagainstPO(FlowEInvoice.java:253)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvoiceagainstPO -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:08:43Z" finished-at="2018-09-27T09:08:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvoiceagainstPO status=FAILURE method=FlowEInvoice.InvoiceagainstPO()[pri:10, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="Statements(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:11, instance:com.main.FlowEInvoice@7a3d45bd]" name="Statements" duration-ms="0" started-at="2018-09-27T09:08:43Z" data-provider="Reconciliation" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:08:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at Framework.ExcelUtils.getRowUsed(ExcelUtils.java:145)
at Framework.ExcelUtils.getRowContains(ExcelUtils.java:129)
at Framework.CommonUtility.dataProvider(CommonUtility.java:381)
at DataProviders.eInvoice_DataProviderTestNG.Reconciliation(eInvoice_DataProviderTestNG.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Statements -->
        <test-method status="SKIP" signature="AddReconciliationStatements(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:12, instance:com.main.FlowEInvoice@7a3d45bd]" name="AddReconciliationStatements" duration-ms="0" started-at="2018-09-27T09:08:43Z" data-provider="Reconciliation" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:08:43Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at Framework.ExcelUtils.getRowUsed(ExcelUtils.java:145)
at Framework.ExcelUtils.getRowContains(ExcelUtils.java:129)
at Framework.CommonUtility.dataProvider(CommonUtility.java:381)
at DataProviders.eInvoice_DataProviderTestNG.Reconciliation(eInvoice_DataProviderTestNG.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddReconciliationStatements -->
        <test-method status="FAIL" signature="Uploads(java.lang.String)[pri:13, instance:com.main.FlowEInvoice@7a3d45bd]" name="Uploads" duration-ms="33337" started-at="2018-09-27T09:08:43Z" data-provider="Uploads" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:09:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Uploads]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:168)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:138)
at com.main.FlowEInvoice.Uploads(FlowEInvoice.java:291)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Uploads -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:09:17Z" finished-at="2018-09-27T09:09:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Uploads status=FAILURE method=FlowEInvoice.Uploads(java.lang.String)[pri:13, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="Batches(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:14, instance:com.main.FlowEInvoice@7a3d45bd]" name="Batches" duration-ms="33354" started-at="2018-09-27T09:09:17Z" data-provider="Batches" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:09:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payment]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Batches]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[846704]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Support]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[HDFC]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:190)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.Batches(FlowEInvoice.java:306)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Batches -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="1" started-at="2018-09-27T09:09:50Z" finished-at="2018-09-27T09:09:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Batches status=FAILURE method=FlowEInvoice.Batches(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:14, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="shareMyReports(java.lang.String, java.lang.String, java.lang.String)[pri:15, instance:com.main.FlowEInvoice@7a3d45bd]" name="shareMyReports" duration-ms="33314" started-at="2018-09-27T09:09:50Z" data-provider="MyReports" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:10:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Reports]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test@test09.com]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:168)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:138)
at com.main.FlowEInvoice.shareMyReports(FlowEInvoice.java:320)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shareMyReports -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="1" started-at="2018-09-27T09:10:24Z" finished-at="2018-09-27T09:10:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=shareMyReports status=FAILURE method=FlowEInvoice.shareMyReports(java.lang.String, java.lang.String, java.lang.String)[pri:15, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="NewBatch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:16, instance:com.main.FlowEInvoice@7a3d45bd]" name="NewBatch" duration-ms="33301" started-at="2018-09-27T09:10:24Z" data-provider="NewBatch" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:10:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payment]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Batches]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[QMS company]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[HDFC]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Admin Z]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[notesDesc]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Admin Z]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:190)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.NewBatch(FlowEInvoice.java:334)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NewBatch -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="1" started-at="2018-09-27T09:10:57Z" finished-at="2018-09-27T09:10:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=NewBatch status=FAILURE method=FlowEInvoice.NewBatch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:16, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="createProcessForm(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:17, instance:com.main.FlowEInvoice@7a3d45bd]" name="createProcessForm" duration-ms="33295" started-at="2018-09-27T09:10:57Z" data-provider="ProcessForm" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:11:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[eForms]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Process forms]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Online Editor]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Auto_form]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Line level form]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Invoice Forms]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[QTS]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Auto_Section]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[Text Field]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[Auto_text]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[formDesc]]>
              </value>
            </param>
            <param index="11">
              <value>
                <![CDATA[sectionDesc]]>
              </value>
            </param>
            <param index="12">
              <value>
                <![CDATA[1 column]]>
              </value>
            </param>
            <param index="13">
              <value>
                <![CDATA[defaultValue]]>
              </value>
            </param>
            <param index="14">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="15">
              <value>
                <![CDATA[FALSE]]>
              </value>
            </param>
            <param index="16">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
            <param index="17">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
            <param index="18">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:190)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:136)
at com.main.FlowEInvoice.createProcessForm(FlowEInvoice.java:354)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createProcessForm -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:11:30Z" finished-at="2018-09-27T09:11:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createProcessForm status=FAILURE method=FlowEInvoice.createProcessForm(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:17, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="Reports(java.lang.String, java.lang.String, java.lang.String)[pri:18, instance:com.main.FlowEInvoice@7a3d45bd]" name="Reports" duration-ms="33341" started-at="2018-09-27T09:11:30Z" data-provider="Reports" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:12:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Reports]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Pre-Packaged Reports]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Early Payment Report]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:168)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:138)
at com.main.FlowEInvoice.Reports(FlowEInvoice.java:367)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Reports -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="1" started-at="2018-09-27T09:12:04Z" finished-at="2018-09-27T09:12:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Reports status=FAILURE method=FlowEInvoice.Reports(java.lang.String, java.lang.String, java.lang.String)[pri:18, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="Workflow(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:19, instance:com.main.FlowEInvoice@7a3d45bd]" name="Workflow" duration-ms="33401" started-at="2018-09-27T09:12:04Z" data-provider="Workflow" depends-on-methods="com.main.FlowEInvoice.Login" finished-at="2018-09-27T09:12:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Workflow]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Invoice]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Auto_Desc]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Subprocess Workflow]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[TRUE]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.Exception">
            <full-stacktrace>
              <![CDATA[java.lang.Exception
at common.Functions.eInvoice_CommonFunctions.navigate_Rainbowpath(eInvoice_CommonFunctions.java:168)
at common.Functions.eInvoice_CommonFunctions.navigateToMainPage(eInvoice_CommonFunctions.java:138)
at com.main.FlowEInvoice.Workflow(FlowEInvoice.java:384)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Workflow -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="getResult" is-config="true" duration-ms="0" started-at="2018-09-27T09:12:37Z" finished-at="2018-09-27T09:12:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Workflow status=FAILURE method=FlowEInvoice.Workflow(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:19, instance:com.main.FlowEInvoice@7a3d45bd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.main.FlowEInvoice@7a3d45bd]" name="tearDown" is-config="true" duration-ms="318" started-at="2018-09-27T09:12:37Z" finished-at="2018-09-27T09:12:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.main.FlowEInvoice -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
